version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: devrestaurant
      MYSQL_USER: devrestaurant
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
